sudo: required
services:
    - docker

before_install:
    - docker build -t aelkhalily/docker-react -f Dockerfile.dev .

#testing using travis with docker container
script:
    - docker run -e CI=true aelkhalily/docker-react npm run test -- --coverage
# deploying using travis to aws
deploy:
    skip_cleanup: true
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docer-react"
    env: "Docerreact-env"
    bucket_name: "elasticbeanstalk-us-east-2-763967860641"
    bucket_path: "docer-react"
    on:
        branch: main
    access_key_id: $AWS_ACCESS_KEY_ID
    Secret_access_key: $AWS_SECRET_KEY_ID
