version: "3.9"
services:
    react-app:
        build:
            context: .
            dockerfile: Dockerfile.dev
        image: aelkhalily/react-app
        ports:
            - "3000:3000"
        volumes:
            - /app/node_modules
            - .:/app
    test:
        image: aelkhalily/react-app
        volumes:
            - /app/node_modules
            - .:/app
        command: ["npm", "run", "test"]
